[package]
name = "codama-koroks"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
quote = "1.0"

[dependencies]
codama-attributes = { path = "../codama-attributes" }
codama-errors = { path = "../codama-errors" }
codama-nodes = { path = "../codama-nodes" }
codama-stores = { path = "../codama-stores" }
codama-syn-helpers = { path = "../codama-syn-helpers" }
derive_more = { version = "1.0", features = ["from"] }
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
