[package]
name = "codama-syn-helpers"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }
codama-syn-helpers-test-macros = { path = "./tests/test-macros" }

[dependencies]
codama-errors = { path = "../codama-errors" }
derive_more = { version = "1.0", features = ["from"] }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
