[package]
name = "codama-syn-helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
codama-errors = { path = "../codama-errors", version = "0.1.0" }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
