[package]
name = "codama"
description = "Generate clients, CLIs, documentation and more from your Solana programs"
version = "0.1.0"
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
codama-errors = { path = "../codama-errors" }
codama-korok-plugins = { path = "../codama-korok-plugins" }
codama-korok-visitors = { path = "../codama-korok-visitors" }
codama-koroks = { path = "../codama-koroks" }
codama-macros = { path = "../codama-macros" }
codama-nodes = { path = "../codama-nodes" }
codama-stores = { path = "../codama-stores" }
proc-macro2 = "1.0"
