[package]
name = "codama-errors"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
quote = "1.0"

[dependencies]
cargo_toml = "0.20"
thiserror = "2.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
