[package]
name = "codama-errors"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_toml = "0.20"
thiserror = "2.0"
proc-macro2 = "1.0"
serde_json = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
