[package]
name = "codama-korok-visitors"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
proc-macro2 = "1.0"
quote = "1.0"

[dependencies]
codama-nodes = { path = "../codama-nodes" }
codama-koroks = { path = "../codama-koroks" }
syn = { version = "2.0", features = ["extra-traits", "full"] }
