[package]
name = "codama-korok-visitors"
description = "Visitors for Korok trees"
version = "0.1.0"
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dev-dependencies]
proc-macro2 = "1.0"
quote = "1.0"
codama-stores = { path = "../codama-stores" }

[dependencies]
cargo_toml = "0.20"
codama-attributes = { path = "../codama-attributes" }
codama-errors = { path = "../codama-errors" }
codama-koroks = { path = "../codama-koroks" }
codama-nodes = { path = "../codama-nodes" }
codama-syn-helpers = { path = "../codama-syn-helpers" }
syn = { version = "2.0", features = ["extra-traits", "full"] }
