[package]
name = "codama-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/mod.rs"

[dev-dependencies]
codama = { path = "../codama" }
trybuild = { version = "1.0.49", features = ["diff"] }

[dependencies]
codama-attributes = { path = "../codama-attributes" }
codama-errors = { path = "../codama-errors" }
codama-koroks = { path = "../codama-koroks" }
codama-stores = { path = "../codama-stores" }
syn = { version = "2.0", features = ["extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
