name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  run_cargo_lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Rustup install nightly
        run: rustup toolchain install nightly
      - name: Rustup install rustfmt
        run: rustup component add rustfmt --toolchain nightly
      - name: Run Cargo fmt
        run: cargo +nightly fmt --all -- --check
      - name: Run Cargo clippy
        run: cargo clippy --all-targets --all-features
  run_cargo_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Run Cargo test
        run: cargo test --all-features