[package]
name = "codama-korok-plugins"
description = "Korok plugins definitions"
version = "0.0.0"
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
codama-errors = { path = "../codama-errors" }
codama-korok-visitors = { path = "../codama-korok-visitors" }
codama-koroks = { path = "../codama-koroks" }
